### ISSUE TITLE
tflite vs. tfrt

### ISSUE THREAD

**Issue by peter197321** [tensorflow/runtime#12]
Is it TensorFlow RT somehow replacing or overriding TensorFlow-Lite? how do you compare side-by-side TensorFlow-Lite and TensorFlow RT?
Does have the TensorFlow RT for the embedded-class device?
Does it have its own mechanisms to access on-device special neural accelerator (NPU) so e.g. no NNAPI is needed to access it?

Thank you.

**Comment by mhong** [comment]
See https://github.com/tensorflow/runtime/issues/6. We'll have more info to share down the road.

**Comment by peter197321** [comment]
OK. is there any plan or roadmap on those decisions - specifically timeline for TFRT?

**Comment by mhong** [comment]
See https://blog.tensorflow.org/2020/04/tfrt-new-tensorflow-runtime.html. We are not ready to share more details beyond that, to avoid over promising.

**Comment by peter197321** [comment]
Thanks for pointing to that info!
