### ISSUE TITLE
build error "error: use 'template' keyword to treat 'get' as a dependent template name"

### ISSUE THREAD

**Issue by vinodgro** [tensorflow/runtime#14]
I get the following error when I follow the build instructions 

ERROR: /runtime/BUILD:613:1: C++ compilation of rule '//:data' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 56 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from lib/data/data_kernels.cc:22:
lib/data/filter_dataset.h:273:33: error: use 'template' keyword to treat 'get' as a dependent template name
    } else if (predicate_value->get<bool>()) {
                                ^
                                template
1 error generated.
Target //tools:bef_executor failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 97.526s, Critical Path: 19.24s
INFO: 370 processes: 370 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by chuanhaozhuge** [comment]
Would you mind pulling the latest version and try again? Seems the culprit line has been updated already (https://github.com/tensorflow/runtime/blob/master/lib/data/filter_dataset.h#L273). Thanks!

**Comment by vinodgro** [comment]
Yes that works fine now. Thanks


> Would you mind pulling the latest version and try again? Seems the culprit line has been updated already (https://github.com/tensorflow/runtime/blob/master/lib/data/filter_dataset.h#L273). Thanks!
