### ISSUE TITLE
TFRT/MLIR as stand-alone executable

### ISSUE THREAD

**Issue by peter197321** [tensorflow/runtime#15]
Since MLIR is a flexible infrastructure doing transformations, is it possible to generate an executable model for the mobile device (target) after the model were prepared/trained - so no runtime such as TensorFlow-lite is needed, and the app can directly use this artifact (executable model)?

**Comment by mhong** [comment]
In theory yes, similar to https://www.tensorflow.org/xla/tfcompile, but this is not something we are prioritizing on. Please feel free to elaborate on the use cases and advocate for this more.

FYI - TFLite infra is lightweight (100's of KBs), including the kernels. It's not clear how much can stand-alone binaries buy us.

**Comment by peter197321** [comment]
What's meant "advocate for this more." ?

**Comment by raziel** [comment]
I think Mingsheng means providing concrete examples/requirements where an executable binary will be better (size, performance, etc.) over the current TFLite approach of interpretable models.

**Comment by peter197321** [comment]
So the idea is that the compiled network model is executed in the standalone mode.  The TFRT/MLIR takes a floating-point model and converts it to a quantized model and apply down the road all optimization need for pre-defined hardware backend. 

So the AOT is used as an option for TFRT/MLIR and the executable output is embedded to application.

So the question is what the TFLite approach to compare to?

**Comment by mhong** [comment]
Thank you for the info. For the referenced benchmark, can you share more concrete pointers, so that we can ideally reproduce the results?

Note the difference in performance might or might not be due to runtime overhead. It also depends on how the kernels are implemented.

**Comment by peter197321** [comment]
Yes, you're right since for TensorFlow-micro are even less promising results

model quant|tensorflow-lite|glow(aot)|tensorflow-lite
-- | -- | --
cifar10 | 65.237 [msec]| 29[msec]|150ms
