### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by nouiz** [tensorflow/runtime#24]
In this document: https://github.com/tensorflow/runtime/blob/master/documents/design_philosophy.md#testing

The URL "MLIR Testing doc" is broken. I wasn't able to find the good URL in the new place of the repository. Does that file still exists? How can I access it?

**Comment by xldrx** [comment]
Thanks you @nouiz for the letting us know about the broken link.
It is been fixed now. In the mean time the correct link is:
https://mlir.llvm.org/getting_started/TestingGuide/

**Comment by xldrx** [comment]
Fixed at 434300f210083bd3e10df65d17bb9d07bac28025

**Comment by nouiz** [comment]
Thanks.

**Comment by mhong** [comment]
Thakn you Hadi!
