### ISSUE TITLE
BTFWriter source code

### ISSUE THREAD

**Issue by raikonenfnu** [tensorflow/runtime#28]
In tools/btf_info_tool/btf_info_test.py, we see that there is a BTFWriter. I think it will be helpful to expose the source code for this so users and contributors can test/experiment with it.

**Comment by raikonenfnu** [comment]
Also would be nice to know the exact encoding used for binary tensor format.

**Comment by chuanhaozhuge** [comment]
Thanks for the interest raikonenfnu@. Just wanna clarify, the BTF format is a temporary format that we use for testing only. We don't plan to use this format in any TensorFlow integration projects.

With that, the BTFWriter is a short Python utility script to write tensors (e.g. numpy arrays)  to the BTF file. We will release it along with other utility scripts.

**Comment by raikonenfnu** [comment]
Thanks @chuanhaozhuge , it's an exciting project, looking forward to it :)

**Comment by JasonMaojinsong** [comment]
@chuanhaozhuge Hi ,  when will you release it,  I also want to use it for some network test, thanks
