### ISSUE TITLE
Output debugging data from within operation kernels

### ISSUE THREAD

**Issue by hidefromkgb** [tensorflow/runtime#30]
This is not an issue but rather a question.

How do I correctly organize debug output from functions that go under `TFRT_KERNEL` in `registry->AddKernel()`?\
I\`ve tried writing something to `stdout`, `stderr` and even to a file, but nothing seems to work.

**Comment by xldrx** [comment]
I assume you are running an mlir test. If this is the case, just remove "| FileCheck %s ..." from the mlir file header and run the test.

**Comment by hidefromkgb** [comment]
@xldrx No, I am running the test like this:
```
$ bazel-bin/tools/tfrt_translate --mlir-to-bef integrationtest/resnet/resnet50_graph_inference.mlir -o=integrationtest/resnet/resnet50_graph_inference.bef
$ bazel-bin/tools/bef_executor --tracing_level=verbose --work_queue_type=s integrationtest/resnet/resnet50_graph_inference.bef
```
Still, surprisingly I get no console output — even though other changes to the target operation alter the final output, so it does get executed.

**Comment by hidefromkgb** [comment]
…wait, does it parse `// RUN:` comments?

**Comment by hidefromkgb** [comment]
Okay. Point taken. Closing the issue as resolved.

P.S.: For anyone having the same problem, MLIR files do parse `// RUN:` comments.

**Comment by xldrx** [comment]
I meant to run a mlir test directly. e.g.
`bazel test mlir_tests/basic_kernels:kernels.mlir.test`

To be clear, a bef file does *NOT* encode any comments including "// RUN:" comments.

To write to the console when running bef files, simply use `TFRT_LOG`. e.g
TFRT_LOG(ERROR) << "::: Hello TFRT!";

Here is an example:
```
~/.tmp/runtime/runtime
Cloud >>> bazel-bin/tools/tfrt_translate --mlir-to-bef mlir_tests/bef_executor/tutorial.mlir | bazel-bin/tools/bef_executor
Choosing memory leak check allocator.
Choosing single-threaded work queue.
--- Running 'hello':
E 2020-10-12 23:26:51.875141 139809547529472 simple_kernels.cc:48] ::: Hello TFRT!
string = hello world
--- Running 'hello_integers':
int32 = 42
--- Running 'print_coordinate':
(2, 4)
```
