### ISSUE TITLE
A question about the tensor-related type system designed in tensor MLIR dialects of TFRT

### ISSUE THREAD

**Issue by Superjomn** [tensorflow/runtime#33]
Hi, I found that all the tensor-related parameters of op definitions are `TensorType`, regardless of the tensor's drvice type(on CUDA, CPU or TPU), sparse or not(COO or Dense).

In the following code snippets, all the **ins** tensors are delcared as `TensorType`, and it seems a general type representing Any tensor type.

https://github.com/tensorflow/runtime/blob/5fb4900ab1b86541589f642f7834bc46b74c4ec9/backends/gpu/include/tfrt/gpu/kernels/cuda_opdefs/cuda_ops.td#L239-L250

https://github.com/tensorflow/runtime/blob/5fb4900ab1b86541589f642f7834bc46b74c4ec9/include/tfrt/tensor/opdefs/coo_host_tensor.td#L44-L61

https://github.com/tensorflow/runtime/blob/5fb4900ab1b86541589f642f7834bc46b74c4ec9/include/tfrt/tensor/opdefs/dense_host_tensor.td#L89-L105

I wonder how TFRT's mlir logic detect the type conflicts when mix using these dialects, for example

```llvm
// create a dense tensor
%a = tfrt_dht.create_uninitialized_tensor.i32.2 [3 : i64, 2 : i64]
// convert a COO tennsor to dense, but the input %a is a dense tensor, broken here
%b, %ch1 = coo.convert_coo_to_dht.i32.0 %a, %ch0
```

It seems that, the `TensorType` in Op definition makes the parameters' type vague, and one can't tell whether a input/output locate on GPU or CPU, or it is a COO Tensor or a Dense Tensor and might write/generate buggy mlir program.

I wonder how TFRT solve above issue?

**Comment by jing-dong** [comment]
You are right that we don't have strong type safety in the TFRT MLIR dialect level. A `TensorType` value can refer to any concrete tensor types, such as dense host tensor, GPU tensor, etc. The thought is that TFRT MLIR dialect is a low-level dialect that is generated by the compiler, so strong type safety is not important. The weak type safety allows us to elide some casting operations, for example casting a 2x3 tensor as a 1x6 tensor, which makes the execution more efficient. That said, it may still make sense to have different MLIR types for the CPU tensor and GPU tensor, as they are not implicily castable. We are still actively evaluating the design here.

**Comment by Superjomn** [comment]
I see, thank you!
