### ISSUE TITLE
Is there a roadmap for TFRT to replace the current runtime of TensorFlow?

### ISSUE THREAD

**Issue by Dounm** [tensorflow/runtime#34]
Hi all, I've seen [the post](https://blog.tensorflow.org/2020/04/tfrt-new-tensorflow-runtime.html) which claims that TFRT will replace the TensorFlow existing runtime. So is there a roadmap or any progress for the replacement process?

**Comment by mhong** [comment]
Hi,

Thank you for checking in. Please see this thread
<https://groups.google.com/a/tensorflow.org/g/tfrt/c/yrunkxBy_as/m/qUWOIoInDAAJ>
for more context.

**Comment by Dounm** [comment]
Thanks, I will follow the thread!
