### ISSUE TITLE
resnet50_graph_inference_tensors.btf not available

### ISSUE THREAD

**Issue by 4vtomat** [tensorflow/runtime#36]
When I wanted to reproduce the tfrt with resnet50 benchmark in the link below, I found that the btf file in google drive was not available, is there any other way to download this file?
https://github.com/tensorflow/runtime/blob/master/documents/resnet.md

**Comment by wanghuancoder** [comment]
> When I wanted to reproduce the tfrt with resnet50 benchmark in the link below, I found that the btf file in google drive was not available, is there any other way to download this file?
> https://github.com/tensorflow/runtime/blob/master/documents/resnet.md

Hi, I have the same problem. Have you found a solution?

**Comment by chuanhaozhuge** [comment]
Sorry for the inconvenience, we updated the [link](https://drive.google.com/file/d/19ltUPerqdLVDnOjjfnlPEyTFFd9P9CQ6/view) to the BTF file. Please try again.
