### ISSUE TITLE
`bazel clean` seems to be broken

### ISSUE THREAD

**Issue by tlemo** [tensorflow/runtime#39]
```
bazel clean
WARNING: Blaze clean does not support starlark options. Ignoring options: [--@rules_cuda//cuda:cuda_targets=sm_60, --@rules_cuda//cuda:compiler=clang]
ERROR: Unrecognized arguments: --@rules_cuda//cuda:cuda_runtime=@tf_runtime//backends/gpu:cuda_stubs
```

Perhaps related to https://github.com/bazelbuild/bazel/issues/11506 ?

**Comment by chsigg** [comment]
Yes, there is a bug in bazel. You can work around it with `bazel --bazelrc=/dev/null clean --expunge`

**Comment by tlemo** [comment]
> You can work around it with bazel --bazelrc=/dev/null clean --expunge

Thanks for the workaround. One small thing though, do you mean `bazel --noworkspace_rc clean --expunge`? 
(`--bazelrc=/dev/null` is documented to ignore any following `--bazelrc` flags and as far as I can tell, it doesn't prevent the workspace .bazelrc from being used)

**Comment by chsigg** [comment]
You are absolutely right. I didn't test the workaround and wasn't aware of this difference between OSS bazel and Google-internal blaze.

**Comment by tlemo** [comment]
No worries. After all, bazel itself still has plenty of leftover blaze references around :)

bazel clean
WARNING: **Blaze** clean ...

**Comment by chsigg** [comment]
`bazel --noworkspace_rc clean --expunge` is the right workaround until bazelbuild/bazel#11506 is fixed. Closing.
