### ISSUE TITLE
Please update GPU support build instructions

### ISSUE THREAD

**Issue by tlemo** [tensorflow/runtime#40]
The current instructions recommend Clang 9 + CUDA 10.2. Unfortunately, Clang 9 only supports CUDA versions up to 10.1.

- Clang 10 (mostly?) works with CUDA 10.2 (although not with CUDA 11.x+). 
- Clang 9 + CUDA 10.1 should be working fine

The compatibility matrix is arguably frustrating, but for those who want to build with Clang (as opposed to GCC + NVCC) it would be helpful if the build instructions mention at least a combination known to work.

**Comment by chsigg** [comment]
I've update the build instructions. I hope this is a little clearer now. I'm closing this issue, but feel free to reopen if something if you would like to add something (or send a PR :grin:).
