### ISSUE TITLE
Please make it easier to build with clang + nvcc

### ISSUE THREAD

**Issue by tlemo** [tensorflow/runtime#41]
While it's already possible to build with clang + nvcc (by hacking `.bazelrc` for example), this combination is not documented and the ergonomics could be improved.

Using clang + nvcc makes it easier to use the latest CUDA SDKs w/o having to switch to GCC.

**Comment by chsigg** [comment]
This should work now:
```
                               # host:  device:
bazel build                ... # clang  clang
bazel build --config=nvcc  ... # clang  nvcc
bazel build --config=gcc   ... #   gcc  nvcc
```
Closing.
