### ISSUE TITLE
Debug build failure with GCC + NVCC

### ISSUE THREAD

**Issue by tlemo** [tensorflow/runtime#44]
When building the debug bits with GCC + NVCC

```
external/local_cuda/cuda/include/crt/host_runtime.h:264: error: undefined reference to '__cudaInitModule'
external/local_cuda/cuda/include/crt/host_runtime.h:264: error: undefined reference to '__cudaInitModule'
external/local_cuda/cuda/include/crt/host_runtime.h:264: error: undefined reference to '__cudaInitModule'
external/local_cuda/cuda/include/crt/host_runtime.h:264: error: undefined reference to '__cudaInitModule'
collect2: error: ld returned 1 exit status
Target //tools:bef_executor failed to build
```

This is the same issue as https://github.com/tensorflow/tensorflow/issues/39280 and the fix is trivial: add `__cudaInitModule` to `cudart_stub.cc`

**Comment by tlemo** [comment]
For reference, here's my local fix: https://github.com/tlemo/runtime/commit/ec851ed4c9efbac46448299379e1aff87acb5308

**Comment by chsigg** [comment]
Hi Leonard, thank you very much for poking at TFRT and reporting all the issues you run into. This is very helpful, and sorry I haven't seen them earlier. I will look into them shortly, please keep them coming!

**Comment by chsigg** [comment]
I submitted Leonard's fix. Closing.
