### ISSUE TITLE
bazel clean gives an error: unrecognized arguments --@rules_cuda

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/runtime#51]
After a fresh clone of the current git tip 46ba4b6db07112a78e849d7306521ecbe8308f83, I can reproduce:

```
$ bazel clean
WARNING: Blaze clean does not support starlark options. Ignoring options: [--@rules_cuda//cuda:cuda_targets=sm_60, --@rules_cuda//cuda:compiler=clang, --@rules_cuda//cuda:copts=-Wno-unknown-cuda-version]
ERROR: Unrecognized arguments: --@rules_cuda//cuda:cuda_runtime=@tf_runtime//backends/gpu:cuda_stubs
```

bazel --version
bazel 4.0.0

I can reproduce this on too very different OSs - Ubuntu 20.04 LTS and CentOS 8.3.2011 with the same bazel version.

**Comment by tlemo** [comment]
Seems to be the same issue as #39

**Comment by chsigg** [comment]
Thanks Leonard. Yes, please use `bazel --noworkspace_rc clean` as a workaround according to #39.
